// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Greeting = require("./Greeting.bs.js");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

console.log("Hello from Reason!");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, Greeting.make("Sebastien", /* array */[])), "root");

/*  Not a pure module */
